travis:
  secure:
    BINSTAR_TOKEN: WKiAIrJIO2+H9EXVTrDoa3wTIfdlV7h96qqeuXDb7smEiwbJTlbA/HwSBCjtQ/kmAuQMmigFJ1Y18Y/5p5nbckCiEo0l3EZRX8KtiEKYG/gROQ6uUrHhJJ7aTOnDbyZW4TUJmKsKs1wj4FGlMkdFejsm/KrX3j6qd+MFtZbS6LTqPXl/64OpMFz+n2tHXXB9nhm0W+PSvuRehi6UhYG3227J27o9ShTlyQyZ6mKst/bJkZ3SNSqACLaBKA0WVUXQQiebO1SfzBhWfCpS5AvqCVt+Gz19ow4si+WsnNHiHYUz5DR/Jy/ElfYQXb6YJI7pryc9dySCi3pQyRPwpTty42M63uq0WX/r6et07eBfWufeb6UbIfBiqyEk+/awiz/RqCEvp8CBlrxmQd4O7bFMKeM2ydThDWFXsc9gN+EEkpiKGcbzVYCMtLNSqGLcCHTR6iped8Vc+MfPoIoDmiKJM1WJsRAM/jZwdR91sJgZekem9iF9SUunKHZE5cL2SIN880wr32ArRyFveHozRLrOvhpU9WqOFYri5RVkIzuoNoYUUXkstgsYmqO20cHstoegHOiS888yEH+aTJPeyZr9gKJ8YRzSYhcpaXR/Nnr7tSX++/FfYoZKXDO5YqJI6HBYVxhzGdTThAUz4XS3U+SHKGUzDXWY0VfjjeVWQ7e9TIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
